// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditCompanyPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void editCompanyPage() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1206, 693));
    driver.findElement(By.id("rootCompanyLink")).click();
    driver.findElement(By.id("seekerLoginLink")).click();
    driver.findElement(By.name("login")).sendKeys("myLogin");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".submit-button")).click();
    driver.findElement(By.linkText("Редактировать")).click();
    assertThat(driver.getTitle(), is("Редактирование информации о компании"));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Газпром");
    driver.findElement(By.name("info")).click();
    driver.findElement(By.name("info")).sendKeys("Государственная нефтяная компания");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2) > span > span")).getText(), is("Газпром"));
    driver.findElement(By.linkText("Мои вакансии")).click();
    driver.findElement(By.linkText("Добавить")).click();
    assertThat(driver.getTitle(), is("Добавить вакансию"));
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("Менеджер");
    driver.findElement(By.cssSelector(".text-center")).click();
    driver.findElement(By.name("salary")).click();
    driver.findElement(By.name("salary")).sendKeys("70000");
    driver.findElement(By.name("requirements")).click();
    driver.findElement(By.name("requirements")).sendKeys("Наличие опыта работы не менее 3 лет");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1) > span")).getText(), is("Менеджер"));
  }
}
