// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationCompanyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationCompany() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1206, 693));
    driver.findElement(By.id("rootCompanyLink")).click();
    driver.findElement(By.id("seekerRegLink")).click();
    assertThat(driver.getTitle(), is("Регистрация"));
    driver.findElement(By.name("login")).sendKeys("myLogin");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector(".indent > .text-center")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".submit-button")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("login")).sendKeys("myLogin");
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector("form > .text-center")).click();
    assertThat(driver.getTitle(), is("Вход"));
    driver.findElement(By.cssSelector(".submit-button")).click();
    assertThat(driver.getTitle(), is("Страница компании"));
  }
}
