// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ResponseToVacancyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void responseToVacancy() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1206, 693));
    driver.findElement(By.id("seekerLoginLink")).click();
    driver.findElement(By.name("login")).sendKeys("SeekerLogin");
    driver.findElement(By.name("password")).sendKeys("pas123");
    driver.findElement(By.cssSelector(".submit-button")).click();
    driver.findElement(By.id("vacanciesListLink")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) a")).click();
    assertThat(driver.getTitle(), is("Информация о вакансии"));
    {
      List<WebElement> elements = driver.findElements(By.linkText("Откликнуться"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Откликнуться")).click();
    driver.findElement(By.id("seekerPageLink")).click();
    driver.findElement(By.linkText("Мои отклики")).click();
    assertThat(driver.findElement(By.cssSelector("td:nth-child(1) > span")).getText(), is("Менеджер"));
    driver.findElement(By.linkText("Подробнее")).click();
    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("Менеджер"));
  }
}
